spring.application.name=booking-service

server.port=8083

spring.datasource.url=jdbc:mysql://localhost:3309/booking_db
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.com.theatre.bookingservice.client.TheatreClient=DEBUG
management.endpoint.health.show-details=always
springdoc.swagger-ui.path=/swagger-ui.html



# ── CIRCUIT BREAKER

# enable Feign to use circuit breaker fallbacks
spring.cloud.openfeign.circuitbreaker.enabled=true

# sliding window — measure the last 10 calls
resilience4j.circuitbreaker.instances.theatre-service.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.theatre-service.sliding-window-size=10

# don't evaluate until at least 5 calls have been made
resilience4j.circuitbreaker.instances.theatre-service.minimum-number-of-calls=5

# trip the circuit if 50% or more calls are failing
resilience4j.circuitbreaker.instances.theatre-service.failure-rate-threshold=50

# stay OPEN (blocking calls) for 10 seconds
resilience4j.circuitbreaker.instances.theatre-service.wait-duration-in-open-state=10s

# allow 3 test calls in HALF_OPEN to check if service recovered
resilience4j.circuitbreaker.instances.theatre-service.permitted-number-of-calls-in-half-open-state=3

# also count slow calls (> 2s) as failures
resilience4j.circuitbreaker.instances.theatre-service.slow-call-duration-threshold=2s
resilience4j.circuitbreaker.instances.theatre-service.slow-call-rate-threshold=50

#metrics

# expose circuit breaker state in /actuator/health
management.health.circuitbreakers.enabled=true
management.endpoints.web.exposure.include=health,metrics,info,circuitbreakers


# http://localhost:8083/actuator/health
